Repository pdfminer/pdfminer.six, pull requests merged in 2019-10, with the labels that each got.

#298 Fix stoke color and non-stroke color in PDFGraphicState
  pdfminer/pdfinterp.py
Labels: bug

#219 use conditional requirements to ensure "chardet" is always required on Python 3
  setup.py
Labels: bug

#203 Interpret font Descent as a negative number even if specified as positive
  pdfminer/pdffont.py
Labels: bug

#132 Fix comparations for image colorspace literals
  pdfminer/image.py
  tests/test_tools_pdf2txt.py
Labels: bug

#246 utils.py: Fixing assertion in drange to allow equal inputs
  pdfminer/utils.py
  tests/test_utils.py
Labels: bug

#306 DRY: Only define dependencies in install_requires
  .travis.yml
  CONTRIBUTING.md
  setup.py
  tox.ini
Labels: development

#311 Pr jbig2
  CHANGELOG.md
  README.md
  pdfminer/image.py
  pdfminer/jbig2.py
  pdfminer/pdftypes.py
  samples/contrib/pdf-with-jbig2.pdf
  tests/test_tools_pdf2txt.py
Labels: enhancement

#205 Add two samples with Type3 fonts
  samples/README
  samples/contrib/matplotlib.pdf
  samples/nonfree/cmp_itext_logo.pdf
  tests/test_tools_pdf2txt.py
Labels: enhancement

#236 use lzw module logger, not the root
  pdfminer/lzw.py
  tests/test_pdfminer_psparser.py
Labels: enhancement

#321 Replace opts by argparse in dumppdf.py
  CHANGELOG.md
  tests/test_tools_dumppdf.py
  tools/dumppdf.py
Labels: enhancement

#315 Layout speedup rebased
  CHANGELOG.md
  pdfminer/layout.py
Labels: type: enhancement
